name: slinkshot_homepage
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sticky_headers: ^0.1.8+1
  frino_icons: ^1.0.1
  ff_navigation_bar: ^0.1.5
  sizer: ^1.1.8
  chewie: ^0.12.2
  video_player: ^1.0.1
  auto_orientation: 1.0.1
  native_device_orientation: ^0.4.3
  color_line_picker: 0.0.1
  cupertino_icons: ^1.0.0
  palette_generator: ^0.2.3

  flutter:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/text/Rubik-VariableFont_wght.ttf

    - family: Bitter
      fonts:
        - asset: assets/text/Bitter-VariableFont_wght.ttf

    - family: Mulish
      fonts:
        - asset: assets/text/Mulish-VariableFont_wght.ttf

  uses-material-design: true
  assets:
    - assets/images/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
